ALTER TABLE employees ADD COLUMN IF NOT EXISTS identity_number VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS address TEXT NOT NULL DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS city VARCHAR(100) NOT NULL DEFAULT '';

DROP TABLE IF EXISTS employee_identities;
