ALTER TABLE shift_days
    ALTER COLUMN check_in TYPE BIGINT
    USING CASE WHEN check_in IS NULL THEN NULL ELSE (EXTRACT(EPOCH FROM check_in::time) * 1000)::BIGINT END,
    ALTER COLUMN check_out TYPE BIGINT
    USING CASE WHEN check_out IS NULL THEN NULL ELSE (EXTRACT(EPOCH FROM check_out::time) * 1000)::BIGINT END,
    ALTER COLUMN break_start TYPE BIGINT
    USING CASE WHEN break_start IS NULL THEN NULL ELSE (EXTRACT(EPOCH FROM break_start::time) * 1000)::BIGINT END,
    ALTER COLUMN break_end TYPE BIGINT
    USING CASE WHEN break_end IS NULL THEN NULL ELSE (EXTRACT(EPOCH FROM break_end::time) * 1000)::BIGINT END;
