app:
  name: "Client API HRIS"
  host: "0.0.0.0"
  port: 9000
  env: "development"
  cookie_secure: false
  cookie_domain:
  prefork: false
  
database:
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  name: "hr_saas"
  sslmode: "disable"
  timezone: "Asia/Jakarta"
  pool:
    idle: 10
    max: 100
    lifetime: 300

log:
  level: "debug"
  format: "text"
