import type { Metadata } from "next";
import Link from "next/link";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Privacy Policy | HR SaaS Admin",
  description:
    "Privacy policy and face data disclosure for HR SaaS attendance features.",
};

const lastUpdated = "16 September 2026";

const reviewerAnswers = [
  {
    question: "What face data does the app collect?",
    answer:
      "The app collects employee face photos captured with the device camera for face enrollment and attendance verification, the employee identifier associated with the face record, face recognition templates or embeddings generated by the internal face recognition service, attendance selfie image URLs, verification status, verification confidence when available, timestamps, location verification results, and device information related to the attendance event. The app does not access Apple Face ID biometric data stored on the device.",
    policySection: "Section 3. Face Data and Biometric Information",
  },
  {
    question:
      "Provide a complete and clear explanation of all planned use, sharing, retention, deletion, and storage practices for the collected face data.",
    answer:
      "Face data is used only to register an employee face profile, verify that the employee performing attendance is the registered employee, prevent attendance fraud, maintain attendance audit records, and support authorized HR administration. Face data is not sold, rented, used for advertising, or used to identify people outside the HR attendance workflow. Enrollment templates are deleted when the employee account is deleted, face registration is reset, or a deletion request is approved, unless retention is required by law. Attendance selfie records are retained as employment, payroll, and audit records for the legally required or company-approved retention period.",
    policySection: "Sections 3, 4, 5, 6, and 7 of this Privacy Policy",
  },
  {
    question:
      "Will the face data be shared with any third parties? Where will this information be stored?",
    answer:
      "Face data is not shared with third parties for their own independent use. It may be processed by service providers that operate the application infrastructure, such as hosting, database, object storage, and the internal face recognition service, only to provide the attendance feature. Face photos are stored in the application's configured S3-compatible object storage or local application storage, face templates are stored by the face recognition service, and attendance references are stored in the application database.",
    policySection: "Sections 5 and 6 of this Privacy Policy",
  },
  {
    question: "How long will face data be retained?",
    answer:
      "Face enrollment templates are retained while the employee account is active and face recognition attendance remains enabled. After account deletion, employment termination, face reset, or an approved deletion request, the enrollment template is deleted within 30 days unless a longer period is required by law. Attendance selfie images and attendance logs are retained only for employment, payroll, legal, and audit needs, then deleted or anonymized when no longer required.",
    policySection: "Section 7. Retention and Deletion of Face Data",
  },
  {
    question:
      "Where in the privacy policy is the app's collection, use, disclosure, sharing, and retention of face data explained?",
    answer:
      "Collection is explained in Section 3. Use is explained in Section 4. Disclosure and sharing are explained in Section 5. Storage is explained in Section 6. Retention and deletion are explained in Section 7. A reviewer-ready quotation is provided in Section 8.",
    policySection: "Sections 3 through 8 of this Privacy Policy",
  },
  {
    question:
      "Quote the specific text from the privacy policy concerning face data.",
    answer:
      "The exact quoted disclosure is provided in Section 8 below so it can be copied into the App Review response without changing the meaning.",
    policySection: "Section 8. Specific Face Data Policy Text",
  },
];

const quotedFacePolicy = [
  "The app collects face photos taken by the employee with the device camera for face enrollment and attendance verification. From those photos, the app's internal face recognition service may generate a face template or embedding linked to the employee ID. The app may also store attendance selfie image URLs, face verification status, face confidence when available, attendance timestamps, location verification results, and device information for the attendance event. The app does not access or collect Apple Face ID biometric data from the device.",
  "Face data is used only to register the employee's face profile, verify that the employee performing attendance is the registered employee, prevent fraudulent attendance, maintain HR attendance audit records, and support authorized HR administration. Face data is not sold, rented, used for advertising, used for tracking across other apps or websites, or used to identify people outside the HR attendance workflow.",
  "Face data is not shared with third parties for their own independent use. Face data may be processed by service providers that operate the application infrastructure, including hosting, database, object storage, and the internal face recognition service, only as necessary to provide and secure the attendance feature. Face photos are stored in the application's configured S3-compatible object storage or local application storage, face templates are stored by the face recognition service, and attendance references are stored in the application database.",
  "Face enrollment templates are retained while the employee account is active and face recognition attendance remains enabled. After account deletion, employment termination, face registration reset, or an approved deletion request, the enrollment template is deleted within 30 days unless a longer retention period is required by law. Attendance selfie images and attendance logs are retained only as long as needed for employment, payroll, legal, and audit purposes, then deleted or anonymized when no longer required.",
];

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-gray-50 text-gray-900">
      <div className="mx-auto max-w-4xl px-6 py-10 sm:py-14">
        <div className="mb-8">
          <Link
            href="/sign-in"
            className="text-sm font-medium text-teal-700 hover:underline"
          >
            Kembali ke login
          </Link>
        </div>

        <article className="rounded-lg bg-white p-6 shadow-sm ring-1 ring-gray-200 sm:p-8">
          <header className="border-b border-gray-200 pb-6">
            <p className="text-sm font-medium text-teal-700">
              HR SaaS Admin
            </p>
            <h1 className="mt-2 text-2xl font-semibold tracking-normal text-gray-950">
              Privacy Policy
            </h1>
            <p className="mt-2 text-sm text-gray-600">
              Last updated: {lastUpdated}
            </p>
            <p className="mt-4 max-w-3xl text-sm leading-6 text-gray-700">
              This Privacy Policy explains how HR SaaS (&quot;we&quot;,
              &quot;our&quot;, or &quot;the application&quot;) collects, uses,
              stores, shares, retains, and deletes personal information for HR
              administration and employee attendance features, including face
              data used for attendance verification.
            </p>
          </header>

          <div className="mt-8 space-y-8">
            <Section title="1. Information We Collect">
              <p>We may collect the following information:</p>
              <ul className="mt-2 list-disc space-y-1 pl-5">
                <li>
                  Identity and employment data, such as name, email address,
                  employee ID, position, division, company, and profile details.
                </li>
                <li>
                  Attendance data, such as check-in, check-out, break,
                  timestamp, location, device information, approval status, and
                  supporting selfie images.
                </li>
                <li>
                  Account and usage data, such as login activity, access logs,
                  permissions, and actions performed in the application.
                </li>
                <li>
                  Device and technical data, such as IP address, browser or
                  mobile device information, operating system, and session data.
                </li>
              </ul>
            </Section>

            <Section title="2. How We Use Information">
              <p>We use personal information to:</p>
              <ul className="mt-2 list-disc space-y-1 pl-5">
                <li>Manage employee accounts, roles, and access permissions.</li>
                <li>
                  Process HR operations, including attendance, leave, payroll,
                  approvals, sanctions, employee documents, and reporting.
                </li>
                <li>
                  Verify attendance events, protect the integrity of attendance
                  records, and reduce unauthorized or fraudulent attendance.
                </li>
                <li>
                  Maintain security, troubleshoot issues, audit system activity,
                  and comply with legal or regulatory obligations.
                </li>
              </ul>
            </Section>

            <Section title="3. Face Data and Biometric Information">
              <p>
                The app collects face photos taken by the employee with the
                device camera for face enrollment and attendance verification.
                From those photos, the app&apos;s internal face recognition
                service may generate a face template or embedding linked to the
                employee ID.
              </p>
              <p className="mt-2">
                The app may also store attendance selfie image URLs, face
                verification status, face confidence when available, attendance
                timestamps, location verification results, and device
                information for the attendance event.
              </p>
              <p className="mt-2">
                The app does not access or collect Apple Face ID biometric data
                stored on the device. Camera access is used only when the
                employee chooses to register a face profile or submit a selfie
                for attendance.
              </p>
            </Section>

            <Section title="4. Planned Use of Face Data">
              <p>Face data is used only for the following purposes:</p>
              <ul className="mt-2 list-disc space-y-1 pl-5">
                <li>Registering the employee&apos;s face profile.</li>
                <li>
                  Verifying that the employee performing attendance is the
                  registered employee.
                </li>
                <li>
                  Preventing fraudulent attendance and maintaining reliable HR
                  attendance records.
                </li>
                <li>
                  Supporting authorized HR administration, audit, dispute
                  review, and security investigation.
                </li>
              </ul>
              <p className="mt-2">
                Face data is not sold, rented, used for advertising, used for
                tracking across other apps or websites, or used to identify
                people outside the HR attendance workflow.
              </p>
            </Section>

            <Section title="5. Sharing and Disclosure of Face Data">
              <p>
                Face data is not shared with third parties for their own
                independent use. Face data may be processed by service providers
                that operate the application infrastructure, including hosting,
                database, object storage, and the internal face recognition
                service, only as necessary to provide and secure the attendance
                feature.
              </p>
              <p className="mt-2">
                Authorized company administrators may view attendance records
                and related selfie images when needed for HR administration,
                audit, approval, payroll, compliance, or dispute review.
              </p>
              <p className="mt-2">
                We may disclose information if required by law, regulation,
                court order, or a valid government request.
              </p>
            </Section>

            <Section title="6. Storage and Security of Face Data">
              <p>
                Face photos are stored in the application&apos;s configured
                S3-compatible object storage or local application storage. Face
                templates or embeddings are stored by the face recognition
                service and linked to the employee ID. Attendance references,
                such as image URLs and verification results, are stored in the
                application database.
              </p>
              <p className="mt-2">
                Access to face data is limited to authorized users and systems
                that need it for the attendance workflow. We use reasonable
                administrative, technical, and organizational controls to protect
                face data from unauthorized access, disclosure, alteration, or
                deletion.
              </p>
            </Section>

            <Section title="7. Retention and Deletion of Face Data">
              <p>
                Face enrollment templates are retained while the employee
                account is active and face recognition attendance remains
                enabled. After account deletion, employment termination, face
                registration reset, or an approved deletion request, the
                enrollment template is deleted within 30 days unless a longer
                retention period is required by law.
              </p>
              <p className="mt-2">
                Attendance selfie images and attendance logs are retained only
                as long as needed for employment, payroll, legal, and audit
                purposes, then deleted or anonymized when no longer required.
                Employees may request deletion or correction through their
                company administrator or the contact listed below.
              </p>
            </Section>

            <Section title="8. Specific Face Data Policy Text">
              <p>
                The following text is the specific privacy policy disclosure
                concerning face data:
              </p>
              <div className="mt-3 space-y-3 rounded-lg border border-gray-200 bg-gray-50 p-4">
                {quotedFacePolicy.map((paragraph) => (
                  <blockquote
                    key={paragraph}
                    className="border-l-2 border-teal-600 pl-3 text-sm leading-6 text-gray-700"
                  >
                    {paragraph}
                  </blockquote>
                ))}
              </div>
            </Section>

            <Section title="9. Apple App Review Face Data Responses">
              <div className="overflow-hidden rounded-lg border border-gray-200">
                <dl className="divide-y divide-gray-200">
                  {reviewerAnswers.map((item) => (
                    <div
                      key={item.question}
                      className="grid gap-3 bg-white p-4 sm:grid-cols-[minmax(0,0.9fr)_minmax(0,1.5fr)]"
                    >
                      <dt className="text-sm font-semibold text-gray-900">
                        {item.question}
                      </dt>
                      <dd className="space-y-2 text-sm leading-6 text-gray-700">
                        <p>{item.answer}</p>
                        <p className="text-xs font-medium text-gray-500">
                          Privacy Policy location: {item.policySection}
                        </p>
                      </dd>
                    </div>
                  ))}
                </dl>
              </div>
            </Section>

            <Section title="10. Cookies and Session Data">
              <p>
                The application may use essential cookies or session storage to
                keep users signed in, remember preferences, and protect the
                service. These technologies are not used for advertising
                tracking.
              </p>
            </Section>

            <Section title="11. User Rights">
              <p>
                Subject to applicable law and company policy, users may request
                access, correction, deletion, or restriction of their personal
                information. Requests should be submitted to the company
                administrator or to the contact listed below.
              </p>
            </Section>

            <Section title="12. Policy Changes">
              <p>
                We may update this Privacy Policy from time to time. Material
                changes will be communicated through the application, email, or
                another appropriate notice method.
              </p>
            </Section>

            <Section title="13. Contact Us">
              <p>
                For questions, privacy requests, or face data deletion requests,
                please contact:
              </p>
              <div className="mt-3 rounded-lg bg-gray-50 p-4 text-sm text-gray-700">
                <p className="font-medium text-gray-900">Tim HR Bank Wonosobo</p>
                <p>Email: admin@bankwonosobo.co.id</p>
              </div>
            </Section>
          </div>
        </article>
      </div>
    </main>
  );
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="text-base font-semibold tracking-normal text-gray-900">
        {title}
      </h2>
      <div className="text-sm leading-6 text-gray-700">{children}</div>
    </section>
  );
}
